### ISSUE TITLE
Failed to run the application

### ISSUE THREAD

**Issue by didiksupriadi41** [flathub/org.apache.netbeans#1]
After installing through flatpak
```bash
$ flatpak install flathub org.apache.netbeans
```
and then run it, this error appeared
```
$ flatpak run org.apache.netbeans

which: no javac in (/app/bin:/usr/bin)
which: no java in (/app/bin:/usr/bin)
Cannot find java. Please use the --jdkhome switch.
```
Actually, I already have javac and java in /usr/bin in my computer.
```
$ ls /usr/bin/ | grep java
...
java
java2html
javac
javadoc
javafxpackager
javap
javapackager
```
Is there any solution to fix this problem ?

**Comment by nedrichards** [comment]
Flatpaks are inside containers so don't use dependencies or binaries on your base system. However, just to check, if you start this from the GUI does it work? Looking at the manifest here it's only setting the JDK location when the app is started from there (which is a bug)

**Comment by nedrichards** [comment]
The app is also failing to install the JDK correctly for some users (that's a different bug). Both of them are easy fixes.

**Comment by nedrichards** [comment]
This should be fixed by https://github.com/flathub/org.apache.netbeans/commit/69695ef19ac28646f618fbd3c94831d4ffd51e21 if you still have issues after this is built and you update, please reopen.

**Comment by patriziobruno** [comment]
Hi @nedrichards,
Thanks for stepping in. I faced the same problem when running from cmdline, all good when running from GUI (.desktop file). I tested your fix locally and it works, both from cmdline and GUI.

**Comment by nedrichards** [comment]
@patriziobruno no worries, I should've spotted that in review tbh, anyway - all good now

**Comment by didiksupriadi41** [comment]
Gratitude @nedrichards @patriziobruno 
:bowing_man: :bowing_man: :bowing_man:

**Comment by patriziobruno** [comment]
@didiksupriadi thanks for taking the time to report the issue
