### ISSUE TITLE
Unable to access svn client

### ISSUE THREAD

**Issue by reinouts** [flathub/org.apache.netbeans#14]
For Subversion projects, Netbeans needs access to the command line svn client.

This is inaccessible within the Flatpak container and I see no way to install it similar to the OpenJDK SDK extension. Basically this means I can't use the Netbeans Flatpak package for my Subversion based projects.

**Comment by patriziobruno** [comment]
The easiest solution would be to release a separate SDK extension with the svn client. I see that nobody has yet done it.
