### ISSUE TITLE
Netbeans remote deployment on raspberrypi returns “make: Makefile: No such file or directory”

### ISSUE THREAD

**Issue by sangar-happy** [flathub/org.apache.netbeans#20]
- I tried to deploy a sample project following [netbeans tutorial][2] it returned followeing output:
```
cd '/home/pi/Documents/netbeansProject/Welcome_1/'
/usr/bin/make -f Makefile CONF=Debug
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.
```
 - All that i got to know after searching about this is make is not able to find the make file named 'Makefile' but i already have it in the project in the 'Important Files' section. Still make cannot find it..
 - The difference that  i noticed from the tutorial  is that i didn't get "Copying project files to..." in the output. Could it be that the Makefile never got to the rasberrypi and that's why it can't find it?
 - I tried opening [remote terminal tab][3] and Netbeans gave error ['Local terminal is not supported on this system'][4] even though i was opening a remote terminal. Although i can ssh into raspberrypi through local terminal easily. (Even with terminal provided in Netbeans)

```
endless version 3.8.0
netbeans version 11.3
```
  [2]: https://netbeans.org/kb/docs/cnd/remotedev-tutorial.html#workflow
  [3]: https://netbeans.org/kb/docs/cnd/remotedev-tutorial.html#terminal
  [4]: https://i.stack.imgur.com/oGtIa.png

**Comment by sangar-happy** [comment]
So I did this and the issue is resolved
~~~
Project properties > Build > Build host > Host configuration check > Selected the host > Properties > Access project files via
~~~
and then selected SFTP(it was System level file sharing earlier) .

I don't know the difference between the two yet, but it worked for me. As i noted earlier, the files weren't copying to the remote host with SFTP.

**Comment by patriziobruno** [comment]
Thanks for sharing your experience and the solution @sangar-happy
