### ISSUE TITLE
Create a beta branch

### ISSUE THREAD

**Issue by batashi** [flathub/org.apache.netbeans#21]
Hi team, 
Could we have a beta branch to deliver Netbeans recent beta build?
This is good for deliver and test quicker.
Give a feel of (upstream linked).

As I understand from documentation, the required only is to create git branch called 'beta'.
I have changed the required for 12.0 beta6. and waiting to push to project repo.

Regards

**Comment by patriziobruno** [comment]
Here it is: https://github.com/flathub/org.apache.netbeans/tree/beta
