### ISSUE TITLE
Unable to detect php interpreter in Ubuntu/Linux Mint

### ISSUE THREAD

**Issue by TonyThuitai** [flathub/org.apache.netbeans#24]
Currently using the netbeans snap package in Linux Mint because the snap package automatically detects the installed php interpreter in the directory: '/usr/bin/php' and can run php site via built in web server (requires php interpreter to be selected). The netbeans flatpak package does not automatically detect an installed php interpreter. When browsing to select the php interpreter file in /usr/bin, the file appears missing. When typing the full path, at the bottom left of the PHP tab in Options dialog says that the php interpreter must be a valid file.

Steps to reproduce the issue:
1. Install php
2. Install both the flatpak and snap packages of Apache netbeans
3. Launch netbeans (can start with either snap or flatpak or both at the same time)
4. Select Tools in the menu bar and select Options in the drop down menu.
5. Select the PHP tab in the Options dialog.
6. Press the search button in the command line section

Expectation: Under the command line section the path of the php interpreter is supposed to be automatically selected and displayed in the PHP interpreter text-box in the flatpak package as the snap package automatically detects it.

Problem: The php interpreter path textbox is blank in the flatpak package and when pressing the browse button to search for the file in /usr/bin directory, the file appears missing in the select php interpreter dialog but it can be seen using a file manager like Nautilus/Nemo. Also when pressing the search button, it says that there are no php interpreters.

**Comment by TonyThuitai** [comment]
Did some research and understood that this issue is caused by the restrictions of flatpak

**Comment by hsPBMG** [comment]
Hi,

i have detected the same issue.

Although php command is working in the shell (/usr/bin/php and /usr/bin/php7.2) Netbeans can't detect the interpreter nor accept the files (/usr/bin/php or /usr/bin/php7.2) in the box 'PHP Interpreter'.

as a result i can't use composer.

maybe it is worth to re-open this issue.

My system is Linux Mint 20 Cinnamon with Netbeans Flatpack 12.4.
The shell command php -v gives PHP 7.2.24-0ubuntu0.18.04.8 (cli) (built: Jul  5 2021 17:41:32) ( NTS )

**Comment by patriziobruno** [comment]
The host's root is available at `/var/run/host`, hence Netbeans will probably have access to the php cli using the path `/var/run/host/usr/bin/php`
