### ISSUE TITLE
Not able to connect to internet from netbeans

### ISSUE THREAD

**Issue by isrgish** [flathub/org.apache.netbeans#36]
I'm running netbeans 12.4 on an Android device in a proot shell that is running a ubuntu dist. I;m using a vnc to connect to it and that's how I have a desktop. I'm able to connect to the internet with Firefox on this desktop without any problems. But in netbeans I get the following error when I tty to check for updates, plugins or anything else that it needs to connect.
**Error Message**
"Unable to connect to the NetBeans Distribution because of java.lang.RuntimeException:     Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter     must be non-empty"
**End Error Message**
I have searched around for a solution and found to `export _JAVA_OPTIONS='-Djava.net.preferIPv4Stack=true'` or to add `-J-Djava.net.preferIPv4Stack=true` to `netbeans_default_options` in `netbeans.conf` file.
I have tried this but without success.

What can I do to resolve this issue?

**Comment by patriziobruno** [comment]
I won't be able to reproduce and I can't say for sure. But it looks like a TLS error of some sorts. Most likely it can't access the trustStore.

**Comment by isrgish** [comment]
I'm new at all this.
Can you explain what is this TLS and what is the trustStore?

Is there anything I can do to help it access this trustStore?

**Comment by isrgish** [comment]
I just upgraded to openjdk 16 and I'm able to download and connect without a problem.

**Comment by patriziobruno** [comment]
Hey  @isrgish, that's great news. Would you mind close this with a comment explaining how you fixed it step by step? Thanks

**Comment by isrgish** [comment]
To fix this issue I installed OpenJDK 16 and made _JAVA_HOME point to it and now I can download.

**Comment by patriziobruno** [comment]
@isrgish did you install the openjdk's flatpak from Flathub?
