### ISSUE TITLE
Javadoc missing for code completion

### ISSUE THREAD

**Issue by swilmet** [flathub/org.apache.netbeans#4]
The Javadoc is missing for code completion in NetBeans.

For example press Ctrl+space after typing in a method:
```
System.out.println
```
There is a message saying “Javadoc not found”.

**Comment by patriziobruno** [comment]
Hi @swilmet,
The Java documentation should be distributed with the appropriate jdk, not with netbeans. You can either download the documentation from https://www.oracle.com/technetwork/java/javase/documentation/jdk11-doc-downloads-5097203.html or open a ticket to https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10 and ask to include the documentation.

Thanks,
Patrizio

**Comment by swilmet** [comment]
Thanks for your quick answer.

> You can either download the documentation from https://www.oracle.com/technetwork/java/javase/documentation/jdk11-doc-downloads-5097203.html

With that way I don't know how to have the Javadoc inside NetBeans when pressing Ctrl+space for the code completion.

The Javadoc must be present inside the Flatpak sandbox I think, so I'll open a ticket for https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10 .

**Comment by patriziobruno** [comment]
@swilmet you can unpack the doc in your home and point netbeans to it. The flatpak has access to your home.

**Comment by patriziobruno** [comment]
Openjdk11 seems to have javadoc, with the upgrade to nb10 we depend on openjdk11 inheriting javadoc
