### ISSUE TITLE
ptrace

### ISSUE THREAD

**Issue by dzhigit1** [flathub/org.apache.netbeans#46]
debugging C programs with GNU Debugger doesn't work because flatpaks can't use ptrace.

**Comment by patriziobruno** [comment]
@dzhigit1 you can change permissions using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) and enable allow=devel
If it's a one-off only, just start Netbeans passing the permission flag from the commandline :
```shell
flatpak run --allow=devel org.apache.netbeans
```

**Comment by dzhigit1** [comment]
I use flatpak run --devel org.apache.netbeans. but it would be helpful if it was documented by netbeans or flatpak allowed it only for IDEs somehow.
