### ISSUE TITLE
Unable to build with external dependency

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.apache.netbeans#5]
Hi,

I'm trying to build this project - https://pagure.io/cico-tools/pagure-scm and it fails on this:
```
Downloading: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/plugin/3.4/plugin-3.4.pom

[ERROR] Some problems were encountered while processing the POMs:
Non-resolvable parent POM for org.jenkinsci.plugins:pagure:1.0-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:3.4 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): Received fatal alert: handshake_failure and 'parent.relativePath' points at no local POM @ line 61, column 13
 @ 
The build could not read 1 project -> [Help 1]
  
  The project org.jenkinsci.plugins:pagure:1.0-SNAPSHOT (/home/zlopez/git/pagure-scm/pom.xml) has 1 error
    Non-resolvable parent POM for org.jenkinsci.plugins:pagure:1.0-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:3.4 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): Received fatal alert: handshake_failure and 'parent.relativePath' points at no local POM @ line 61, column 13 -> [Help 2]
```

I tried to visit the link outside netbeans and it's working fine.

**Comment by patriziobruno** [comment]
As far as I can tell the problem could has the same route cause to #3. To work around it it you can replace HTTPS with HTTP for your maven repository or set a different trusted key store for maven, one that contains the root certificate to repo.jenkins-ci.org's,  [here you'll find the instructions, just change MAVEN_OPTS to suit your needs](https://maven.apache.org/guides/mini/guide-repository-ssl.html).

On this side I'll add a build step for the package that would add a whole bunch of trusted certificates to JDK's cacerts keystore, in order to prevent this sort of problems.

**Comment by Zlopez** [comment]
I changed the url to HTTP and this solved the issue. Thanks

**Comment by Zlopez** [comment]
Ok, now I'm getting this when building with `JAVA_HOME=/app/jdk /app/netbeans/java/maven/bin/mvn install`:
```
java.nio.file.NoSuchFileException: MYPATH/target/classes/META-INF/annotations/hudson.Extension
```

I found this [issue](https://stackoverflow.com/questions/51046821/java-nio-file-nosuchfileexception-target-classes-meta-inf-annotations-hudson-e/51048894) on stackoverflow, but because the `JAVA_HOME` is explicitly defined I don't think this is it.

I also tried to install NetBeans plugin for Jenkins/Stapler development as mentioned [here](https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial), but no luck so far.

**Comment by patriziobruno** [comment]
Can you trying installing org.freedesktop.Sdk.Extension.openjdk10 and changing JAVA_HOME to /usr/lib/sdk/openjdk10.

**Comment by patriziobruno** [comment]
It looks as though maven prior to 3.5 has problems with jdk higher than 8. You can try installing the maven wrapper to run a more recent version of maven:
```
sudo flatpak enter $(ps ax | grep java.*netb | grep -v grep|tail -1 | awk '{print $1}') bash
mkdir -p ~/maven/bin
cd ~/maven/bin
JAVA_HOME=/app/jdk mvn mvn -N io.takari:maven:wrapper
```
Then you need to get netbeans use the maven wrapper by adding it to netbeans' options: Tools->Options->Java->Maven->Execution->Maven Home and you add your wrapper's directory ~/maven. Don't mind the "Invalid Maven installation directory" message, it should work despite that.
![image](https://user-images.githubusercontent.com/2834179/49077781-150a0700-f234-11e8-9bf0-87c8f83f30ac.png)

**Comment by Zlopez** [comment]
@patriziobruno 
Is this permanent solution, or only for running flatpak?
I ask because of this part `$(ps ax | grep java.*netb | grep -v grep|tail -1 | awk '{print $1}')`

**Comment by patriziobruno** [comment]
@Zlopez this installs mvnw in your home dir, so permanent

**Comment by patriziobruno** [comment]
This is a known issue: https://issues.jenkins-ci.org/browse/JENKINS-52024

**Comment by Zlopez** [comment]
Still no luck, I did what you suggested, but this time I got:
```
/var/home/zlopez/maven/bin/mvn: line 257: /var/home/zlopez/git/pagure-scm/.mvn/wrapper/maven-wrapper.properties: No such file or directory
```
when running `cd /var/home/zlopez/git/pagure-scm; JAVA_HOME=/app/jdk M2_HOME=/var/home/zlopez/maven /var/home/zlopez/maven/bin/mvn install`

**Comment by Zlopez** [comment]
I also noticed a strange issue, if the netbeans is not on the primary monitor it doesn't show any context menu or dropdown options. It just highlights the selection.
For example, if you click on tools it is highlighted, but no menu appears. If you move the window to primary monitor, it starts working.

**Comment by patriziobruno** [comment]
I'm surprised that the wrapper is looking for the properties file in your src project dir. It should be looking for in in /var/home/zlopez/.mvn/wrapper/maven-wrapper.properties

**Comment by Zlopez** [comment]
Maybe there is something I'm missing here.

**Comment by Zlopez** [comment]
Ok, I found out, why it is looking inside git for properties file. It is using relative path `.mvn/wrapper/maven-wrapper.properties` and the first thing the netbeans does on build is to change to project folder `cd /var/home/zlopez/git/pagure-scm`. I think, this is a correct behavior, but I'm not sure why it wants to have properties file there.

**Comment by Zlopez** [comment]
I copied only the error message earlier, but here is the whole output:
```
cd /var/home/zlopez/git/pagure-scm; JAVA_HOME=/app/jdk M2_HOME=/var/home/zlopez/maven /var/home/zlopez/maven/bin/mvn install
/var/home/zlopez/maven/bin/mvn: line 257: /var/home/zlopez/git/pagure-scm/.mvn/wrapper/maven-wrapper.properties: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /var/home/zlopez/git/pagure-scm/.mvn/wrapper/maven-wrapper.jar: No 
Warning: such file or directory

  4 48337    4  2220    0     0  10724      0  0:00:04 --:--:--  0:00:04 10724
curl: (23) Failed writing body (0 != 2220)
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

It looks like the issue is currently with curl, not with wrapper.

**Comment by Zlopez** [comment]
@patriziobruno 
Do you have any advice on this?

**Comment by patriziobruno** [comment]
@Zlopez sorry I couldn't reproduce your behaviour with other projects (it works in thoses cases) and I haven't had the time to pull pagure-scm and test on it myself.

**Comment by patriziobruno** [comment]
unable to reproduce and no recent updates
