### ISSUE TITLE
Unable to install new plugins (Install button not clickable).

### ISSUE THREAD

**Issue by sangar-happy** [flathub/org.apache.netbeans#6]
The _Install_ button in the **Available Plugins** section and _Activate_, _Deactivate_ and _Uninstall_ buttons in the **Installed** section are not clickable. At first I had issue #3 and I changed the URL to http which fixed it but still I cannot install a plugin.

**Comment by sangar-happy** [comment]
Ive even tried to reinstall the IDE, still these buttons are not clickable. Also I cannot  create new C/C++, HTML projects.

**Comment by sangar-happy** [comment]
Okay wow just discovered this can be done by left-clicking on the plugin 🤦

**Comment by patriziobruno** [comment]
Hi @sangar-happy, sorry I missed this issue, I'm glad you managed to install the plugins. Another way is to left-click the column "Install" on the left-hand side of the plugin name, there's a checkbox and you can select as many plugins as you want before hitting the Install button on the bottom of the window.

![image](https://user-images.githubusercontent.com/2834179/50229051-527c3300-03a1-11e9-8b10-9305f6b28f50.png)

**Comment by sangar-happy** [comment]
yeah the checkbox outline couldn't be seen so yeah :3

**Comment by patriziobruno** [comment]
I've stumbled in the same issue myself, I'm not sure if it is a poor design choice or a theme issue.
