### ISSUE TITLE
Branding issues

### ISSUE THREAD

**Issue by patriziobruno** [flathub/org.apache.netbeans#9]
As kindly reported by NetBeans' maintainer @vieiro, NetBeans must be written with a capital B: https://netbeans.org/about/history.html

**Comment by vieiro** [comment]
Thanks @patriziobruno ! This is very kind of you!

**Comment by patriziobruno** [comment]
@vieiro that's the least I could do :) I'll go through the proper channels to ask the NetBeans' team who you want to appoint to manage this repository.
